# Generated by Django 3.0.5 on 2023-11-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
