# Generated by Django 4.2.7 on 2023-11-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_testdetails_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdetails',
            name='course_name',
        ),
        migrations.AddField(
            model_name='testdetails',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
            preserve_default=False,
        ),
    ]
