# Generated by Django 4.2.7 on 2023-11-14 14:33

from django.db import migrations, models
import django.utils.timezone
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_testdetails_course_name_testdetails_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course',
            new_name='course_id',
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='end_time',
            field=models.DateTimeField(default=quiz.models.calculate_end_time),
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testdetails',
            name='total_marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
