# Generated by Django 4.2.7 on 2023-11-14 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_rename_course_question_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetails',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
