# Generated by Django 4.2.7 on 2023-11-14 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_testdetails_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='testno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.testdetails'),
            preserve_default=False,
        ),
    ]
