# Generated by Django 4.2.7 on 2023-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_result_testno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_id',
            field=models.IntegerField(),
        ),
    ]
