# Generated by Django 4.2.7 on 2023-11-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_salary'),
        ('quiz', '0019_alter_course_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
