# Generated by Django 4.2.7 on 2023-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_course_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='testno',
            field=models.IntegerField(default=0),
        ),
    ]
