# Generated by Django 4.2.7 on 2023-11-20 06:54

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_alter_question_testno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetails',
            name='start_time',
            field=models.DateTimeField(default=quiz.models.calculate_start_time),
        ),
    ]
