# Generated by Django 3.0.5 on 2023-11-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20231105_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
