# Generated by Django 4.2.7 on 2023-11-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country_code',
            field=models.CharField(default=91, max_length=5),
            preserve_default=False,
        ),
    ]
